name: DisasterResponseProject
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - click=7.1.2
  - flask=1.1.2
  - icc_rt=2019.0.0
  - intel-openmp=2020.2
  - itsdangerous=1.1.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - markupsafe=1.1.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - nltk=3.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1j
  - pandas=1.2.2
  - pip=21.0.1
  - plotly=4.14.3
  - python=3.8.8
  - python-dateutil=2.8.1
  - pytz=2021.1
  - regex=2020.11.13
  - retrying=1.3.3
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlalchemy=1.3.23
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tqdm=4.56.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wincertstore=0.2
  - zlib=1.2.11

